# Use an official OpenJDK runtime as a base image
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file built by Maven to the container
COPY target/demo-0.0.1-SNAPSHOT.jar /app/demo.jar

# Expose port 8080 to access the app from outside
EXPOSE 8080

# Run the JAR file when the container starts
ENTRYPOINT ["java", "-jar", "demo.jar"]
